apiVersion: v1
kind: Service
metadata:
  name: sample-app7-svc
spec:
  type: NodePort
  selector:
    app: app
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app7-canary
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: app
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app7-stable
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: app
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sample-app7-vsvc
spec:
  gateways:
  - istio-rollout-gateway
  hosts:
  - app.sample-app7.api.adeptmind.net
  http:
  - name: primary
    route:
    - destination:
        host: sample-app7-stable
      weight: 100
    - destination:
        host: sample-app7-canary
      weight: 0
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
 name: istio-rollout-gateway
spec:
 selector:
   istio: ingressgateway # use Istio default gateway implementation
 servers:
 - port:
     number: 80
     name: http
     protocol: HTTP
   hosts:
   - "app.sample-app7.api.adeptmind.net"
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app7-lb
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: app
